name: using cache-react
on:
    workflow_dispatch: 
        inputs:
            use-cache:
                type: boolean
                default: true
                description: Wheteher to ececute cache step
            node-choice:
                type: choice
                description: provide the node version
                options:
                  - 18.x
                  - 20.x
                  - 21.x
                default: 20.x     
jobs:
    
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: react-app
        steps:
            - name: checkout-code
              uses:  actions/checkout@v4
           
            - name: Setup-the-node
              uses: actions/setup-node@v3
              with:
                  node-version: ${{inputs.node-choice}}
            - name: Download-cached-dep
              id: cache
              uses: actions/cache@v3
              if: ${{inputs.use-cache}}
              with:
                key: deps-node-module-${{hashFiles('react-app/package-lock.json')}}
                path: react-app/node_modules

            - name: install the dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: npm ci  
            - name: Testing
              run: npm run test
            - name: build
              run: npm run build               
            - name: Deploying to non prod
              run: echo "Deploying to nonprod"