name: using cache-react
on:
    workflow_dispatch: 
        inputs:
            use-cache:
                type: boolean
                default: true
                description: Wheteher to ececute cache step
            node-choice:
                type: choice
                description: provide the node version
                options:
                  - 18.x
                  - 20.x
                  - 21.x
                default: 20.x     
jobs:
    
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: react-app
        steps:
            - name: checkout-code
              uses:  actions/checkout@v4
           
            - name: Setup-the-node
              uses: actions/setup-node@v3
              with:
                  node-version: ${{inputs.node-choice}}
            - name: install the dependencies
              run: npm ci  
            - name: Testing
              run: npm run test
            - name: build
              run: npm run build               
            - name: Deploying to non prod
              run: echo "Deploying to nonprod"